version: '3'

services:
  api-dev:
    build: ./api
    #depends_on:
    #  - postgres
    command:
      - /bin/bash
      - -c
      - |
        # TODO: Workaround until setuptools implements PEP-660
        touch setup.cfg
        pip install -e .
        rm -f setup.cfg
        pip install -r requirements.txt
        flask run --host=0.0.0.0

    environment:
      # NOTE: DO NOT USE THIS IN PRODUCTION!!!
      - FLASK_APP=mediaserv.app:app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONPATH=/home/flask/.local/lib/python3.9/
    ports:
      - "5000:5000"
    volumes:
      - ./api/:/home/flask/app/api
      - ${MEDIASERV_DATA_PATH}:/data/music
      - ./sqlite-db:/var/lib/sqlite/data
      - ./images:/var/local/mediaserv/images

  ui-dev:
    build: ./ui
    depends_on:
      - api-dev
    # NOTE: DO NOT USE THIS IN PRODUCTION!!!
    command: yarn dev
    environment:
      - API_URI=${APP_API_URI:-http://localhost:5000}
      - WEBSOCKET_URI=${APP_WEBSOCKET_URI:-ws://localhost:5000}
    ports:
      - "3000:3000"
    volumes:
      - ./ui/:/home/ui/

  postgres:
    restart: always
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=development-only
      - POSTGRES_PASSWORD=development-only
      - POSTGRES_DB=momento-api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
