"""empty message

Revision ID: 45776d9cc554
Revises: c4ef08b4f1ae
Create Date: 2022-07-29 01:23:41.543182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45776d9cc554'
down_revision = 'c4ef08b4f1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('scan', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'updated_on')
    op.drop_column('scan', 'created_on')
    # ### end Alembic commands ###
