"""empty message

Revision ID: 9b9caa6dd6ef
Revises: 88c4de219c7f
Create Date: 2022-08-02 01:43:36.600105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9caa6dd6ef'
down_revision = '88c4de219c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('num_discs', sa.Integer(), nullable=False))
    op.add_column('album', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('album', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('track', sa.Column('disc_number', sa.Integer(), nullable=False))
    op.add_column('track', sa.Column('track_number', sa.Integer(), nullable=False))
    op.add_column('track', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('track', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('track', sa.Column('encoding', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'encoding')
    op.drop_column('track', 'updated_on')
    op.drop_column('track', 'added_on')
    op.drop_column('track', 'track_number')
    op.drop_column('track', 'disc_number')
    op.drop_column('album', 'updated_on')
    op.drop_column('album', 'added_on')
    op.drop_column('album', 'num_discs')
    # ### end Alembic commands ###
