"""empty message

Revision ID: d8654f636771
Revises: 9b9caa6dd6ef
Create Date: 2022-08-03 01:09:13.015226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8654f636771'
down_revision = '9b9caa6dd6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'year')
    # ### end Alembic commands ###
